Annotations
1 error and 1 warning
triage
failed now in 5s
Search logs
1s
1s
Run actions/labeler@v4
The configuration file (path: .github/labeler.yml) isn't not found locally, fetching via the api
Warning: The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions
Error: Resource not accessible by integration
